### ISSUE TITLE
Crash on attempting to add a non-existing file

### ISSUE THREAD

**Issue by lwp-ygavrilenko** [lwp-emelnik/musicintervals2anki#127] opened 2021-06-09 12:39 UTC
Steps to reproduce:
1. Select or capture a file, fill in mandatory fields;
2. Close the application and delete the selected file from the filesystem;
3. Open the application and click 'Add to anki'.

**Comment by Andrej-Adamenko** [comment] 2021-06-09 13:32
The steps are like this for me:
1. Select some files in MI2A
2. Without closing the application switch to another application
3. Remove some of the selected files from the file system
4. Switch back to MI2A

The application MI2A crashed immediately on switching to it, without any additional input from me. I would not be able to click "Add to Anki" or anything else anyway, because it crashed before I was able to do anything.

**Comment by lwp-vinokurova** [comment] 2021-06-10 11:16
The same issue is reproduced when user renamed selected files from the file system.
The application MI2A crashed immediately on switching to it. See screenshot. 
![image](https://user-images.githubusercontent.com/85628357/121515920-5f1ff600-c9f6-11eb-96d0-02e2d46c7e34.png)

**Comment by lwp-vinokurova** [comment] 2021-07-16 09:23
Tested: 
- correct error is displayed for user when file is deleted/renamed
user should select new/again

**Closed by lwp-vinokurova** 2021-07-16 09:23 UTC
Labels: bug
